package com.orwima.premierleaguearchitect

data class Player(
    val name: String = "",
    val image: String = "",
    val team: String = "",
    val positions: List<String> = emptyList()
)

data class Lineup(
    val team: String = "",
    val formation: String = "",
    val positions: Map<String, String> = emptyMap()
)
/*
object PlayerRepository {
    val allPlayers = listOf(
        Player(name = "K. Havertz", image = R.drawable.havertz, team = "Arsenal", positions = listOf("ST", "CAM")),
        Player(name = "G. Jesus", image = R.drawable.g_jesus, team = "Arsenal", positions = listOf("ST")),
        Player(name = "G. Martinelli", image = R.drawable.martinelli, team = "Arsenal", positions = listOf("LW")),
        Player(name = "L. Trossard", image = R.drawable.trossard, team = "Arsenal", positions = listOf("LW")),
        Player(name = "B. Saka", image = R.drawable.saka, team = "Arsenal", positions = listOf("RW")),
        Player(name = "E. Nwaneri", image = R.drawable.nwaneri, team = "Arsenal", positions = listOf("CAM", "RW")),
        Player(name = "R. Sterling", image = R.drawable.sterling, team = "Arsenal", positions = listOf("LW", "RW")),
        Player(name = "M. Odegaard", image = R.drawable.odegaard, team = "Arsenal", positions = listOf("CAM", "CM")),
        Player(name = "D. Rice", image = R.drawable.rice, team = "Arsenal", positions = listOf("CDM", "CM")),
        Player(name = "W. Saliba", image = R.drawable.saliba, team = "Arsenal", positions = listOf("CB")),
        Player(name = "Gabriel M.", image = R.drawable.gabriel, team = "Arsenal", positions = listOf("CB")),
        Player(name = "B. White", image = R.drawable.white, team = "Arsenal", positions = listOf("RB", "CB")),
        Player(name = "J. Timber", image = R.drawable.timber, team = "Arsenal", positions = listOf("RB", "CB", "LB")),
        Player(name = "T. Partey", image = R.drawable.partey, team = "Arsenal", positions = listOf("CDM", "RB", "CM")),
        Player(name = "M. Merino", image = R.drawable.merino, team = "Arsenal", positions = listOf("CM", "CDM")),
        Player(name = "Jorginho", image = R.drawable.jorginho, team = "Arsenal", positions = listOf("CDM", "CM")),
        Player(name = "R. Calafiori", image = R.drawable.calafiori, team = "Arsenal", positions = listOf("LB", "CB")),
        Player(name = "O. Zinchenko", image = R.drawable.zinchenko, team = "Arsenal", positions = listOf("LB", "CM", "LM")),
        Player(name = "J. Kiwior", image = R.drawable.kiwior, team = "Arsenal", positions = listOf("CB", "LB")),
        Player(name = "K. Tierney", image = R.drawable.tierney, team = "Arsenal", positions = listOf("LB", "LM")),
        Player(name = "M. Lewis-Skelly", image = R.drawable.lewis_skelly, team = "Arsenal", positions = listOf("LB", "CM", "LM")),
        Player(name = "T. Tomiyasu", image = R.drawable.tomiyasu, team = "Arsenal", positions = listOf("RB", "LB", "CB", "RM")),
        Player(name = "D. Raya", image = R.drawable.raya, team = "Arsenal", positions = listOf("GK")),
        Player(name = "Neto", image = R.drawable.neto, team = "Arsenal", positions = listOf("GK")),

        Player(name = "N. Jackson", image = R.drawable.jackson, team = "Chelsea", positions = listOf("ST")),
        Player(name = "C. Nkunku", image = R.drawable.nkunku, team = "Chelsea", positions = listOf("ST", "CAM")),
        Player(name = "J. Sancho", image = R.drawable.sancho, team = "Chelsea", positions = listOf("LW", "RW")),
        Player(name = "P. Neto", image = R.drawable.p_neto, team = "Chelsea", positions = listOf("RW", "LW", "LM", "RM")),
        Player(name = "J. Felix", image = R.drawable.felix, team = "Chelsea", positions = listOf("ST", "CAM", "LW")),
        Player(name = "M. Mudryk", image = R.drawable.mudryk, team = "Chelsea", positions = listOf("LW", "RW", "LM", "RM")),
        Player(name = "M. Guiu", image = R.drawable.guiu, team = "Chelsea", positions = listOf("ST")),
        Player(name = "N. Madueke", image = R.drawable.madueke, team = "Chelsea", positions = listOf("RW", "RM")),
        Player(name = "C. Palmer", image = R.drawable.palmer, team = "Chelsea", positions = listOf("CAM", "RW")),
        Player(name = "C. Casadei", image = R.drawable.casadei, team = "Chelsea", positions = listOf("CM", "CDM")),
        Player(name = "C. Chukwuemeka", image = R.drawable.chukwuemeka, team = "Chelsea", positions = listOf("CM", "CAM")),
        Player(name = "K. Dewsbury-Hall", image = R.drawable.dewsbury_hall, team = "Chelsea", positions = listOf("CM", "CAM", "CDM")),
        Player(name = "E. Fernandez", image = R.drawable.e_fernandez, team = "Chelsea", positions = listOf("CM", "CDM", "CAM")),
        Player(name = "R. Lavia", image = R.drawable.lavia, team = "Chelsea", positions = listOf("CDM", "CM")),
        Player(name = "M. Caicedo", image = R.drawable.caicedo, team = "Chelsea", positions = listOf("CDM", "CM")),
        Player(name = "R. James", image = R.drawable.r_james, team = "Chelsea", positions = listOf("RB", "RM")),
        Player(name = "M. Gusto", image = R.drawable.gusto, team = "Chelsea", positions = listOf("RB", "LB", "RM", "LM")),
        Player(name = "B. Chilwell", image = R.drawable.chilwell, team = "Chelsea", positions = listOf("LB", "LM")),
        Player(name = "M. Cucurella", image = R.drawable.cucurella, team = "Chelsea", positions = listOf("LB", "LM")),
        Player(name = "R. Veiga", image = R.drawable.r_veiga, team = "Chelsea", positions = listOf("CB", "LB", "CM")),
        Player(name = "T. Chalobah", image = R.drawable.chalobah, team = "Chelsea", positions = listOf("CB")),
        Player(name = "T. Adarabioyo", image = R.drawable.tosin, team = "Chelsea", positions = listOf("CB")),
        Player(name = "B. Badiashile", image = R.drawable.badiashile, team = "Chelsea", positions = listOf("CB")),
        Player(name = "W. Fofana", image = R.drawable.fofana, team = "Chelsea", positions = listOf("CB")),
        Player(name = "A. Disasi", image = R.drawable.disasi, team = "Chelsea", positions = listOf("CB")),
        Player(name = "L. Colwill", image = R.drawable.colwill, team = "Chelsea", positions = listOf("CB")),
        Player(name = "R. Sanchez", image = R.drawable.r_sanchez, team = "Chelsea", positions = listOf("GK")),
        Player(name = "F. Jorgensen", image = R.drawable.jorgensen, team = "Chelsea", positions = listOf("GK")),
        Player(name = "M. Bettinelli", image = R.drawable.bettinelli, team = "Chelsea", positions = listOf("GK")),

        Player(name = "D. Nunez", image = R.drawable.d_nunez, team = "Liverpool", positions = listOf("ST")),
        Player(name = "D. Jota", image = R.drawable.jota, team = "Liverpool", positions = listOf("ST", "LW")),
        Player(name = "L. Diaz", image = R.drawable.l_diaz, team = "Liverpool", positions = listOf("LW", "ST")),
        Player(name = "C. Gakpo", image = R.drawable.gakpo, team = "Liverpool", positions = listOf("LW", "ST")),
        Player(name = "M. Salah", image = R.drawable.salah, team = "Liverpool", positions = listOf("RW", "ST")),
        Player(name = "F. Chiesa", image = R.drawable.chiesa, team = "Liverpool", positions = listOf("RW", "LW")),
        Player(name = "A. Mac Allister", image = R.drawable.mac_allister, team = "Liverpool", positions = listOf("CM", "CAM", "CDM")),
        Player(name = "D. Szoboszlai", image = R.drawable.szoboszlai, team = "Liverpool", positions = listOf("CAM", "CM")),
        Player(name = "C. Jones", image = R.drawable.c_jones, team = "Liverpool", positions = listOf("CM", "CAM")),
        Player(name = "H. Elliott", image = R.drawable.elliott, team = "Liverpool", positions = listOf("CAM", "CM")),
        Player(name = "R. Gravenberch", image = R.drawable.gravenberch, team = "Liverpool", positions = listOf("CDM", "CM")),
        Player(name = "W. Endo", image = R.drawable.endo, team = "Liverpool", positions = listOf("CDM", "CM")),
        Player(name = "T. Morton", image = R.drawable.morton, team = "Liverpool", positions = listOf("CDM", "CM")),
        Player(name = "A. Robertson", image = R.drawable.robertson, team = "Liverpool", positions = listOf("LB", "LM")),
        Player(name = "K. Tsimikas", image = R.drawable.tsimikas, team = "Liverpool", positions = listOf("LB", "LM")),
        Player(name = "T. Alexander-Arnold", image = R.drawable.alexander_arnold, team = "Liverpool", positions = listOf("RB", "CM", "CDM", "RM")),
        Player(name = "C. Bradley", image = R.drawable.bradley, team = "Liverpool", positions = listOf("RB", "RM")),
        Player(name = "V. van Dijk", image = R.drawable.van_dijk, team = "Liverpool", positions = listOf("CB")),
        Player(name = "I. Konate", image = R.drawable.konate, team = "Liverpool", positions = listOf("CB")),
        Player(name = "J. Quansah", image = R.drawable.quansah, team = "Liverpool", positions = listOf("CB")),
        Player(name = "J. Gomez", image = R.drawable.j_gomez, team = "Liverpool", positions = listOf("CB", "RB")),
        Player(name = "Alisson", image = R.drawable.alisson, team = "Liverpool", positions = listOf("GK")),
        Player(name = "C. Kelleher", image = R.drawable.kelleher, team = "Liverpool", positions = listOf("GK")),
        Player(name = "V. Jaros", image = R.drawable.jaros, team = "Liverpool", positions = listOf("GK")),

        Player(name = "E. Haaland", image = R.drawable.haaland, team = "Man City", positions = listOf("ST")),
        Player(name = "O. Marmoush", image = R.drawable.marmoush, team = "Man City", positions = listOf("ST", "LW")),
        Player(name = "J. Doku", image = R.drawable.doku, team = "Man City", positions = listOf("LW", "RW")),
        Player(name = "J. Grealish", image = R.drawable.grealish, team = "Man City", positions = listOf("LW", "CAM")),
        Player(name = "P. Foden", image = R.drawable.foden, team = "Man City", positions = listOf("RW", "LW", "CAM")),
        Player(name = "Savinho", image = R.drawable.savinho, team = "Man City", positions = listOf("RW", "LW")),
        Player(name = "O. Bob", image = R.drawable.bob, team = "Man City", positions = listOf("RW", "RM")),
        Player(name = "B. Silva", image = R.drawable.b_silva, team = "Man City", positions = listOf("CAM", "RW")),
        Player(name = "K. De Bruyne", image = R.drawable.de_bruyne, team = "Man City", positions = listOf("CAM", "CM")),
        Player(name = "C. Echeverri", image = R.drawable.echeverri, team = "Man City", positions = listOf("CAM")),
        Player(name = "J. McAtee", image = R.drawable.mcatee, team = "Man City", positions = listOf("CAM", "CM")),
        Player(name = "M. Nunes", image = R.drawable.nunes, team = "Man City", positions = listOf("CM", "RB", "RM", "LM")),
        Player(name = "M. Kovačić", image = R.drawable.kovacic, team = "Man City", positions = listOf("CM", "CDM")),
        Player(name = "I. Gundogan", image = R.drawable.gundogan, team = "Man City", positions = listOf("CM", "CAM")),
        Player(name = "Rodri", image = R.drawable.rodri, team = "Man City", positions = listOf("CDM", "CM")),
        Player(name = "J. Gvardiol", image = R.drawable.gvardiol, team = "Man City", positions = listOf("LB", "CB")),
        Player(name = "R. Lewis", image = R.drawable.lewis, team = "Man City", positions = listOf("RB", "LB", "CDM", "RM")),
        Player(name = "R. Dias", image = R.drawable.dias, team = "Man City", positions = listOf("CB")),
        Player(name = "M. Akanji", image = R.drawable.akanji, team = "Man City", positions = listOf("CB")),
        Player(name = "N. Ake", image = R.drawable.ake, team = "Man City", positions = listOf("CB", "LB")),
        Player(name = "J. Stones", image = R.drawable.stones, team = "Man City", positions = listOf("CB", "CDM")),
        Player(name = "A. Khusanov", image = R.drawable.khusanov, team = "Man City", positions = listOf("CB")),
        Player(name = "Ederson", image = R.drawable.ederson, team = "Man City", positions = listOf("GK")),
        Player(name = "S. Ortega", image = R.drawable.ortega, team = "Man City", positions = listOf("GK")),
        Player(name = "S. Carson", image = R.drawable.carson, team = "Man City", positions = listOf("GK")),

        Player(name = "R. Hojlund", image = R.drawable.hojlund, team = "Man United", positions = listOf("ST")),
        Player(name = "J. Zirkzee", image = R.drawable.zirkzee, team = "Man United", positions = listOf("ST")),
        Player(name = "M. Rashford", image = R.drawable.rashford, team = "Man United", positions = listOf("LW", "ST")),
        Player(name = "A. Garnacho", image = R.drawable.garnacho, team = "Man United", positions = listOf("LW", "RW")),
        Player(name = "A. Diallo", image = R.drawable.diallo, team = "Man United", positions = listOf("RW", "CAM", "RM")),
        Player(name = "B. Fernandes", image = R.drawable.fernandes, team = "Man United", positions = listOf("CAM", "CM")),
        Player(name = "M. Mount", image = R.drawable.mount, team = "Man United", positions = listOf("CAM", "CM")),
        Player(name = "K. Mainoo", image = R.drawable.mainoo, team = "Man United", positions = listOf("CM", "CDM")),
        Player(name = "C. Eriksen", image = R.drawable.eriksen, team = "Man United", positions = listOf("CM", "CDM", "CAM")),
        Player(name = "M. Ugarte", image = R.drawable.ugarte, team = "Man United", positions = listOf("CDM", "CM")),
        Player(name = "Casemiro", image = R.drawable.casemiro, team = "Man United", positions = listOf("CDM", "CM")),
        Player(name = "T. Collyer", image = R.drawable.collyer, team = "Man United", positions = listOf("CDM", "CM")),
        Player(name = "L. Shaw", image = R.drawable.shaw, team = "Man United", positions = listOf("LB", "LM")),
        Player(name = "D. Dalot", image = R.drawable.dalot, team = "Man United", positions = listOf("RB", "LB", "RM", "LM")),
        Player(name = "N. Mazraoui", image = R.drawable.mazraoui, team = "Man United", positions = listOf("RB", "LB", "RM", "LM")),
        Player(name = "L. Yoro", image = R.drawable.yoro, team = "Man United", positions = listOf("CB")),
        Player(name = "L. Martinez", image = R.drawable.l_martinez, team = "Man United", positions = listOf("CB", "CDM")),
        Player(name = "M. de Ligt", image = R.drawable.de_ligt, team = "Man United", positions = listOf("CB")),
        Player(name = "H. Maguire", image = R.drawable.maguire, team = "Man United", positions = listOf("CB")),
        Player(name = "V. Lindelof", image = R.drawable.lindelof, team = "Man United", positions = listOf("CB")),
        Player(name = "J. Evans", image = R.drawable.evans, team = "Man United", positions = listOf("CB")),
        Player(name = "A. Onana", image = R.drawable.a_onana, team = "Man United", positions = listOf("GK")),
        Player(name = "A. Bayindir", image = R.drawable.bayindir, team = "Man United", positions = listOf("GK")),

        Player(name = "D. Solanke", image = R.drawable.solanke, team = "Tottenham", positions = listOf("ST")),
        Player(name = "Richarlison", image = R.drawable.richarlison, team = "Tottenham", positions = listOf("ST", "LW")),
        Player(name = "Heung-min Son", image = R.drawable.son, team = "Tottenham", positions = listOf("LW", "ST")),
        Player(name = "T. Werner", image = R.drawable.werner, team = "Tottenham", positions = listOf("LW", "ST")),
        Player(name = "M. Moore", image = R.drawable.moore, team = "Tottenham", positions = listOf("LW")),
        Player(name = "B. Johnson", image = R.drawable.johnson, team = "Tottenham", positions = listOf("RW", "ST")),
        Player(name = "W. Odobert", image = R.drawable.odobert, team = "Tottenham", positions = listOf("RW", "LW", "CAM")),
        Player(name = "J. Maddison", image = R.drawable.maddison, team = "Tottenham", positions = listOf("CAM", "CM")),
        Player(name = "D. Kulusevski", image = R.drawable.kulusevski, team = "Tottenham", positions = listOf("CAM", "RW")),
        Player(name = "P. M. Sarr", image = R.drawable.sarr, team = "Tottenham", positions = listOf("CM", "CDM")),
        Player(name = "L. Bergvall", image = R.drawable.bergvall, team = "Tottenham", positions = listOf("CM", "CDM")),
        Player(name = "Y. Bissouma", image = R.drawable.bissouma, team = "Tottenham", positions = listOf("CDM", "CM")),
        Player(name = "R. Bentancur", image = R.drawable.bentancur, team = "Tottenham", positions = listOf("CDM", "CM")),
        Player(name = "P. Porro", image = R.drawable.porro, team = "Tottenham", positions = listOf("RB", "RM")),
        Player(name = "A. Gray", image = R.drawable.gray, team = "Tottenham", positions = listOf("RB", "CB")),
        Player(name = "D. Spence", image = R.drawable.spence, team = "Tottenham", positions = listOf("RB", "LB", "RM", "LM")),
        Player(name = "D. Udogie", image = R.drawable.udogie, team = "Tottenham", positions = listOf("LB", "LM")),
        Player(name = "C. Romero", image = R.drawable.romero, team = "Tottenham", positions = listOf("CB")),
        Player(name = "M. van de Ven", image = R.drawable.van_de_ven, team = "Tottenham", positions = listOf("CB", "LB")),
        Player(name = "R. Dragusin", image = R.drawable.dragusin, team = "Tottenham", positions = listOf("CB")),
        Player(name = "B. Davies", image = R.drawable.davies, team = "Tottenham", positions = listOf("CB", "LB")),
        Player(name = "G. Vicario", image = R.drawable.vicario, team = "Tottenham", positions = listOf("GK")),
        Player(name = "A. Kinsky", image = R.drawable.kinsky, team = "Tottenham", positions = listOf("GK")),
        Player(name = "F. Forster", image = R.drawable.forster, team = "Tottenham", positions = listOf("GK")),

        Player(name = "O. Watkins", image = R.drawable.watkins, team = "Aston Villa", positions = listOf("ST")),
        Player(name = "J. Duran", image = R.drawable.duran, team = "Aston Villa", positions = listOf("ST")),
        Player(name = "L. Bailey", image = R.drawable.bailey, team = "Aston Villa", positions = listOf("RW")),
        Player(name = "D. Malen", image = R.drawable.malen, team = "Aston Villa", positions = listOf("RW", "LW", "ST")),
        Player(name = "J. Ramsey", image = R.drawable.ramsey, team = "Aston Villa", positions = listOf("LW")),
        Player(name = "M. Rogers", image = R.drawable.rogers, team = "Aston Villa", positions = listOf("CAM", "LW")),
        Player(name = "E. Buendia", image = R.drawable.buendia, team = "Aston Villa", positions = listOf("CAM", "LW", "RW")),
        Player(name = "Y. Tielemans", image = R.drawable.tielemans, team = "Aston Villa", positions = listOf("CM", "CDM", "CAM")),
        Player(name = "J. McGinn", image = R.drawable.mcginn, team = "Aston Villa", positions = listOf("CAM", "LW", "RW", "CM")),
        Player(name = "R. Barkley", image = R.drawable.barkley, team = "Aston Villa", positions = listOf("CM", "CAM", "CDM")),
        Player(name = "A. Onana", image = R.drawable.onana, team = "Aston Villa", positions = listOf("CDM", "CM")),
        Player(name = "B. Kamara", image = R.drawable.kamara, team = "Aston Villa", positions = listOf("CDM", "CM", "CB")),
        Player(name = "I. Maatsen", image = R.drawable.maatsen, team = "Aston Villa", positions = listOf("LB", "LM")),
        Player(name = "L. Digne", image = R.drawable.digne, team = "Aston Villa", positions = listOf("LB", "LM")),
        Player(name = "M. Cash", image = R.drawable.cash, team = "Aston Villa", positions = listOf("RB", "LM")),
        Player(name = "K. Nedeljković", image = R.drawable.nedeljkovic, team = "Aston Villa", positions = listOf("RB", "RM")),
        Player(name = "A. Garcia", image = R.drawable.garcia, team = "Aston Villa", positions = listOf("RB", "RM")),
        Player(name = "P. Torres", image = R.drawable.torres, team = "Aston Villa", positions = listOf("CB")),
        Player(name = "E. Konsa", image = R.drawable.konsa, team = "Aston Villa", positions = listOf("CB", "RB")),
        Player(name = "T. Mings", image = R.drawable.mings, team = "Aston Villa", positions = listOf("CB")),
        Player(name = "K. Hause", image = R.drawable.hause, team = "Aston Villa", positions = listOf("CB")),
        Player(name = "E. Martinez", image = R.drawable.e_martinez, team = "Aston Villa", positions = listOf("GK")),
        Player(name = "J. Gauci", image = R.drawable.gauci, team = "Aston Villa", positions = listOf("GK")),
        Player(name = "R. Olsen", image = R.drawable.olsen, team = "Aston Villa", positions = listOf("GK")),

        Player(name = "A. Isak", image = R.drawable.isak, team = "Newcastle", positions = listOf("ST")),
        Player(name = "C. Wilson", image = R.drawable.wilson, team = "Newcastle", positions = listOf("ST")),
        Player(name = "W. Osula", image = R.drawable.osula, team = "Newcastle", positions = listOf("ST")),
        Player(name = "A. Gordon", image = R.drawable.gordon, team = "Newcastle", positions = listOf("LW", "RW")),
        Player(name = "H. Barnes", image = R.drawable.barnes, team = "Newcastle", positions = listOf("LW", "RW")),
        Player(name = "M. Almiron", image = R.drawable.almiron, team = "Newcastle", positions = listOf("RW", "CAM")),
        Player(name = "J. Murphy", image = R.drawable.murphy, team = "Newcastle", positions = listOf("RW")),
        Player(name = "Joelinton", image = R.drawable.joelinton, team = "Newcastle", positions = listOf("CM", "LW")),
        Player(name = "S. Tonali", image = R.drawable.tonali, team = "Newcastle", positions = listOf("CM", "CDM")),
        Player(name = "J. Willock", image = R.drawable.willock, team = "Newcastle", positions = listOf("CM")),
        Player(name = "S. Longstaff", image = R.drawable.longstaff, team = "Newcastle", positions = listOf("CM")),
        Player(name = "L. Miley", image = R.drawable.miley, team = "Newcastle", positions = listOf("CM")),
        Player(name = "B. Guimaraes", image = R.drawable.bruno, team = "Newcastle", positions = listOf("CDM", "CM")),
        Player(name = "L. Hall", image = R.drawable.hall, team = "Newcastle", positions = listOf("LB", "LM")),
        Player(name = "M. Targett", image = R.drawable.targett, team = "Newcastle", positions = listOf("LB", "LM")),
        Player(name = "T. Livramento", image = R.drawable.livramento, team = "Newcastle", positions = listOf("RB", "RM", "LB")),
        Player(name = "K. Trippier", image = R.drawable.trippier, team = "Newcastle", positions = listOf("RB", "RM", "LB")),
        Player(name = "E. Krafth", image = R.drawable.krafth, team = "Newcastle", positions = listOf("RB", "RM")),
        Player(name = "S. Botman", image = R.drawable.botman, team = "Newcastle", positions = listOf("CB")),
        Player(name = "L. Kelly", image = R.drawable.kelly, team = "Newcastle", positions = listOf("CB", "LB")),
        Player(name = "F. Schar", image = R.drawable.schar, team = "Newcastle", positions = listOf("CB")),
        Player(name = "D. Burn", image = R.drawable.burn, team = "Newcastle", positions = listOf("CB", "LB")),
        Player(name = "J. Lascelles", image = R.drawable.lascelles, team = "Newcastle", positions = listOf("CB")),
        Player(name = "N. Pope", image = R.drawable.pope, team = "Newcastle", positions = listOf("GK")),
        Player(name = "O. Vlachodimos", image = R.drawable.vlachodimos, team = "Newcastle", positions = listOf("GK")),
        Player(name = "M. Dubravka", image = R.drawable.dubravka, team = "Newcastle", positions = listOf("GK")),
        Player(name = "J. Ruddy", image = R.drawable.ruddy, team = "Newcastle", positions = listOf("GK")),
    )
}*/